server:
  port: 8080
spring:
  profiles:
    default: dev
  config:
    import:
      - application-db.yml
      - application-debug.yml
      - application-rendering.yml
      - application-security.yml