server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    check-template-location: true

  devtools:
    livereload:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 896670349972-3ov2qlo4kk9enln0nomnje2lkmmsrdh4.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: 844a386b0e59266a047e
            client-secret: 761c67c2b90d5be8415e105f534b7ce220445f1b
          kakao:
            scope:
              - openid
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-id: 2e457d5bc429ed4b1b00a234e0acfc2f
            client-secret: u3d8x1I5jbYI8zPD6Q3s4qG8bp6Dvjm3
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            client-name: Naver
            client-id: OcZqX2trakWWRmaBX0FV
            client-secret: WL2gzRA9t6

        provider:
          kakao:
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo #https://kapi.kakao.com/v2/user/me
            user-name-attribute: sub #id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basicauth_user?serverTimezone=Asia/Seoul
    username: root
    password: 11111111

  data:
    redis:
      port: 6379
      host: localhost

  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false
        generate_statistics: true

logging:
  level:
    org.springframework.security: trace
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace