spring:
  config:
    activate:
      on-profile: dev

  thymeleaf:
    cache: false
    check-template-location: true

  devtools:
    livereload:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

  thymeleaf:
    cache: false
    check-template-location: true

  devtools:
    livereload:
      enabled: false